export default {
  plus: '+',
  minus: '−',
  //plusMinus: '±',
  times: '×',
  division: '÷',
  fraction: '/',
  //infinity: '∞',
  equals: '=',
  notEquals: '≠',
  //approximatelyEqual: '≈',
  //equivalentTo: '≡',
  //congruentTo: '≅',
  //therefore: '∴',
  //because: '∵',
  //sumation: '∑'
  //product: '∏',
  //integral: '∫',
  //derivative: '∂',
  //root: '√',
  //degrees: '°',
  //all: '∀',
  //exists: '∃'
  //elementOf: '∈'
  //implies: '⇒'
  //ifAndOnlyIf: '⇔'
  //subset: '⊂'
  //subsetEquals: '⊆'
  //notSubset: '⊄'
  //empty: '∅'
  //and: '∧'
  //or: '∨'
  //not: '¬'
  //circledPlus: '⊕'
  //circledTimes: '⊗'
  less: '<',
  greater: '>',
  lessEquals: '≤',
  greaterEquals: '≥',
  //capitalSigma: 'Σ',
  //capitalPi: 'Π',
  //capitalGamma: 'Γ',
  //capitalLambda: 'Λ',
  //capitalDelta: 'Δ',
  //alpha: 'α',
  //beta: 'β',
  //gamma: 'γ',
  //delta: 'δ',
  //theta: 'θ',
  //lambda: 'λ',
  //mu: 'μ',
  //pi: 'π',
  //phi: 'φ',
  //omega: 'ω',
  exponent: '^',
};
